# Generated by Django 4.1.1 on 2022-09-22 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_account_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(default='No Address', max_length=100),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=20, unique=True)),
                ('last_location', models.CharField(max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
