# Generated by Django 4.1.1 on 2022-09-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_alter_account_address_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.TextField(default='No Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
