# Generated by Django 4.1.1 on 2022-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_alter_account_address_alter_vehicle_last_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
