# Generated by Django 4.1.1 on 2022-09-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_vehicle_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('license_no', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(default='No Address', max_length=200)),
                ('vehicle', models.ManyToManyField(to='front.vehicle')),
            ],
        ),
    ]
