# Generated by Django 4.1.1 on 2022-09-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
