# Generated by Django 4.1.1 on 2022-09-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_driver_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
