# Generated by Django 4.1.1 on 2022-09-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_rename_vehicle_driver_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
