# Generated by Django 4.1.1 on 2022-09-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_account_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.CharField(choices=[('ri', 'right_index'), ('rm', 'right_middle'), ('rr', 'right_ring'), ('rl', 'right_little'), ('rt', 'right_thumb'), ('li', 'left_index'), ('lm', 'left_middle'), ('lr', 'left_ring'), ('ll', 'left_little'), ('lt', 'left_thumb')], max_length=20)),
                ('img', models.ImageField(upload_to='prints')),
                ('of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.driver')),
            ],
        ),
    ]
