# Generated by Django 4.1.1 on 2022-09-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default='01923240000', max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default='01923240000', max_length=20),
        ),
    ]
