# Generated by Django 4.1 on 2022-09-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='finger_scan')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Intruder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='Intruders')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('finger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.finger')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_result', models.BooleanField(blank=True, null=True)),
                ('match_time', models.FloatField(blank=True, null=True)),
                ('match_percent', models.FloatField(blank=True, null=True)),
                ('transport_time', models.FloatField(blank=True, null=True)),
                ('transport_medium', models.CharField(blank=True, max_length=30, null=True)),
                ('photo_time', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('finger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.finger')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.intruder')),
            ],
        ),
    ]
