# Generated by Django 4.1 on 2022-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='depth',
            field=models.IntegerField(default=100),
        ),
    ]
